version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: todos-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: secfix_user
      POSTGRES_PASSWORD: secfix_password
      POSTGRES_DB: todos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
